version: '3'
services:
  db_postgres:
    image: postgres:10-alpine
    volumes:
      - ./db_data:/data
    ports:
      - '5430:5432'
    environment:
      PGDATA: /data
      POSTGRES_DB: aeon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db_nosql_redis:
    image: redis:alpine
    volumes:
      - ./db_data:/redis
    ports:
      - '6380:6379'
